### ISSUE TITLE
seeing build failures in gh actions builds that need this package

### ISSUE THREAD

**Issue by cartazio** [RyanGlScott/code-page#4]
see https://github.com/cartazio/ralist/runs/1421746860?check_suite_focus=true 

no clue why ... 
```
Failed to build code-page-0.2.
Build log (
C:\Users\runneradmin\AppData\Roaming\cabal\logs\ghc-8.10.2\code-page-0.2-40b31d8410d325f256dc55ba2f1c5be0d24a6cd7.log
cabal.exe: Failed to build code-page-0.2 (which is required by
):
bench:benchmarking from ralist-0.3.0.0). See the build log above for details.
Preprocessing library for code-page-0.2..

Building library for code-page-0.2..
[1 of 3] Compiling System.Win32.CodePage ( dist\build\System\Win32\CodePage.hs, dist\build\System\Win32\CodePage.o )
ghc.exe: could not execute: C:/GitLabRunner/builds/2WeHDSFP/0/ghc/ghc/inplace/mingw/bin/ld.exe
Error: Process completed with exit code 1.
```

**Comment by RyanGlScott** [comment]
This is [GHC#18550](https://gitlab.haskell.org/ghc/ghc/-/issues/18550), an upstream GHC bug. [This comment](https://gitlab.haskell.org/ghc/ghc/-/issues/18550#note_309996) indicates that if you use GHC 8.10.2.1 or later from Chocolatey, then it will contain a workaround for that bug.

**Comment by cartazio** [comment]
Grr.  Ok. So I guess Next step is poke the setup-Haskell gh actions repo
folks

**Comment by RyanGlScott** [comment]
Sounds good. In any case, this isn't an issue on `code-page`'s side, so I'm going to close this. Please re-open if you disagree.
